### ISSUE TITLE
Complete confirming talks and add moderators

### ISSUE THREAD

**Issue by pietroppeter** [pietroppeter/nim-fosdem#9]
as in mail by Agk:

> We're aiming for the vast majority of the schedule to be ready and published by
> the end of the break, Tuesday 4th Jan 2022.   This includes making sure
> every 'event' has a moderator assigned to it. 
> 
> At that point every participant will get a standard email containing their
> personal schedule for them to check.
> 
> Then the rest of that week is for validation, tweaking and fixing problems etc.
> 
> By Friday 7th January the schedule should be considered frozen, with only
> unavoidable or essential changes allowed after that time.
> 
> Then we switch our focus to obtaining the videos.
> 
> Alasdair

by today we should complete the confirmation of talks and make sure everything appears on the website correctly.
We should also assign "moderators" to every event. I was thinking to have @PMunch be a moderator for first 3 talks, @dom96 to be moderator for next 3, and me to be moderator of last 3. It is possible that in our own talks (mine and @PMunch we cannot be both moderator and speaker), if that happens we could have me being a moderator in @PMunch talk and @PMunch being a moderator in mine. Since we also have 3 other volounteers (@FedericoCeratto, @moigagoo, @xigoi) we could add them as backup moderators each of them to a block of 3 talks: would you have preferences for a block?

Having said that I have no clue what a moderator does or should do, if anyone does please let me know :)

**Comment by pietroppeter** [comment]
ha, found an answer about moderators in this PR (merged!): https://github.com/FOSDEM/website/pull/170/commits/dd98f2a8577b414b88985c5db38124d82c78662c

relevant excerpt

> ## During the event
> 
> ### Online event
> 
> The online version of the event consist in one main matric fosdem-specific chatroom by devroom. This chat room has a video stream component which streams the content of the devroom along the day. It has also a text chat component open to any audience registered in https://chat.fosdem.org. Audience can also watch teh stream withour registration in which case they can't interact in the chatroom.
> 
> The video stream is composed of:
> 
> - prerecorded video talk which are started automatically following the scheduling
> - live video jitsee instance for Q&A , panel discussion, BOF are started automatically: for event with video, the jitsi starts as soon as the video is finishied; for event without video (panel, BOF), it will start at the beginning of the event. 
> 
> On top of the public main devroom chatroom, there are managers/speakers only chatroom used to organize the event:
> 
> - each talk with Q&A or panel disucssion has a dedicated room witha jitsi video conf component
> - #yourdevroom-backstage is the place were devroom managers and speakers can meet or exchange privately
> - #devroom-managers channel to ask for help or soordinate with org team or other rooms.
> 
> During the online event, devrooms managers have to moderate their chatroom with consist in:
> 
> - moderate the main public chatroom discussion and note questions to speakers to fuel Q&A/panel discussion
> - be connected to the backstage channel in case speakers needs help
> - Talk moderators have to be connected and welcome speakers in the talk specific channel 10 minutes between the talk starts to test the video conf component and prepare for the live Q&A/discussion panel. The moderator has to then animate the discussion by posing questions taken from the main chatroom audience or some of their own. The live jitsi video conf which is streamed to the audience right after the talk video ends. Speaker can share their screen if a specific question needs a demo or else.

**Comment by pietroppeter** [comment]
I think we should also add the 5' Q&A to duration for each talk (instead of having 5' of break) - found confirmation of this in FOSDEM matrix chat: https://matrix.to/#/!HiMrQwoxwdnWgrTVly:matrix.org/$FMBsnkGKmPACt4gm5_0R9Mpe9KHvXFukp5HQp2FjMK8?via=libera.chat&via=matrix.org&via=fosdem.org

**Comment by pietroppeter** [comment]
schedule completed: https://fosdem.org/2022/schedule/track/nim_programming_language/

moderators still to be done, waiting for feedback on above proposal:

> We should also assign "moderators" to every event. I was thinking to have @PMunch be a moderator for first 3 talks, @dom96 to be moderator for next 3, and me to be moderator of last 3. It is possible that in our own talks (mine and @PMunch we cannot be both moderator and speaker), if that happens we could have me being a moderator in @PMunch talk and @PMunch being a moderator in mine. Since we also have 3 other volounteers (@FedericoCeratto, @moigagoo, @xigoi) we could add them as backup moderators each of them to a block of 3 talks: would you have preferences for a block?

**Comment by moigagoo** [comment]
If I may pick, I'd like the block with Enu in it. I love the project, it'll be my honor to moderate the talk. Also, Nimib is very dear to my heart.

**Comment by pietroppeter** [comment]
talks about Enu and Nimib in principle are two different blocks but I do not see why you cannot be a moderator for both :)

**Comment by moigagoo** [comment]
> talks about Enu and Nimib in principle are two different blocks but I do not see why you cannot be a moderator for both :)

What I meant was, I'd be happy to moderate either Enu's or Nimib's block equally :-)

**Comment by pietroppeter** [comment]
ping @PMunch, @dom96:

> moderators still to be done, waiting for feedback on above proposal:
> 

> > We should also assign "moderators" to every event. I was thinking to have @PMunch be a moderator for first 3 talks, @dom96 to be moderator for next 3, and me to be moderator of last 3. It is possible that in our own talks (mine and @PMunch we cannot be both moderator and speaker), if that happens we could have me being a moderator in @PMunch talk and @PMunch being a moderator in mine. Since we also have 3 other volounteers (@FedericoCeratto, @moigagoo, @xigoi) we could add them as backup moderators each of them to a block of 3 talks: would you have preferences for a block?

**Comment by PMunch** [comment]
We can't have the moderator and speaker be the same person, so we can either do the simple switch you propose, or we can use our other volunteers for this.

After the talk there is a short Q&A, the moderator is tasked with reading through the questions and posing these to the speaker (obviously merging questions if they are very similar etc.). For this to work the best the moderator should have some level of knowledge within the field (probably not the biggest issue with a room with such sharp focus as this one).

When the Q&A is done then the moderator and speaker are put in a separate channel while the next talk starts, this is to mimic the "hallway" and to allow people with more questions to have "hallway discussions" with the speaker. At this point people can join via audio/video and the moderator is there to ensure that everything goes smoothly (but not really ask questions themselves, although they can if they want to of course). This means that a moderator is a bit busy also after the actual talk finishes, so it would be best to not have two talks right after another as moderator. Best would be to simply interleave moderation so it's spaced out as much as possible.

**Comment by pietroppeter** [comment]
ok good to know.

then I guess each one of us can pick 2 or 3 talks using the above constraints (don't be a moderator in two subsequent talks, speakers cannot be moderators in their talk or next one). There is 6 of us and 9 talks we should be able to have 1-2 moderators per talk (we could have exactly 2 if we all pick 3 and we distribute well). @dom96, @xigoi, @FedericoCeratto, @PMunch: *Pick your fighter!* (I already put in @moigagoo according to his preferences and selected 3 for me)

| Who | What | Moderators |
|-----|------|----------|
| araq | Nim concurrency Past, Present and Future |  |
| pmunch | Next generation micro-controller programming | @pietroppeter |
| arthurrasmusson | LibVF.IO: vGPU & SR-IOV on Consumer GPUs using Nim |  |
| rlipsc | Polymorph: a compile time approach to entity-component-systems in Nim | @pietroppeter |
| scott wadden | Potato Zombies - Helping a 6 year old build a 3d game using Enu and Nim | @moigagoo |
| oakes | Pararules - A Nim rules engine for reactive programs and games | @pietroppeter |
| ayman-albaz | From Python to Nim, a preliminary introduction to performance optimization |  |
| pietroppeter | State of Scientific Computing in Nim 2022 | @moigagoo |
| treeform | Real World Metaprogramming with Nim  |  |

**Comment by PMunch** [comment]
I placed myself as far as possible away from my talk as possible. Whether I take both or just one of them is more or less the same for me.

| Who | What | Moderators |
|-----|------|----------|
| araq | Nim concurrency Past, Present and Future |  |
| pmunch | Next generation micro-controller programming | @pietroppeter |
| arthurrasmusson | LibVF.IO: vGPU & SR-IOV on Consumer GPUs using Nim |  |
| rlipsc | Polymorph: a compile time approach to entity-component-systems in Nim | @pietroppeter |
| scott wadden | Potato Zombies - Helping a 6 year old build a 3d game using Enu and Nim | @moigagoo |
| oakes | Pararules - A Nim rules engine for reactive programs and games | @pietroppeter |
| ayman-albaz | From Python to Nim, a preliminary introduction to performance optimization | @PMunch |
| pietroppeter | State of Scientific Computing in Nim 2022 | @moigagoo |
| treeform | Real World Metaprogramming with Nim  | @PMunch  |

**Comment by pietroppeter** [comment]
since we did not put the moderator in the system this morning an automatic script  assigned all devroom managers to all talks and the situation is a bit messy. According to a recent mail by fosdem there are two expected roles: coordinator and host. 

>  At least one speaker
  At least one coordinator (devroom manager) 
    - I've a script that I run occasionally that will add these if you don't
  At least one host (the person who will work with the speaker to ensure
    they upload a suitable presentation, and who will host the live Q&A session)
    - Hosts only need a normal self-created pentabarf account, like a
      speaker (not a devroom manager).  Adding them to the event with
      the 'host' role gives them access to what they need.

We will need to realign according to this. I should be able to work on this during the weekend but help is much welcome. After this is done we should share on the forum the finalized schedule.

**Comment by dom96** [comment]
Soo I had a look and it seems everyone is a coordinator on all talks. Based on what @pietroppeter wrote above it seems we actually need for each talk 1 coordinator/moderator and 1 host. Should we pick different mods/hosts or just make coordinators and hosts the same?

If the latter shall we change the coords to be:

| Who | What | Moderators |
|-----|------|----------|
| araq | Nim concurrency Past, Present and Future | @dom96 |
| pmunch | Next generation micro-controller programming | @pietroppeter |
| arthurrasmusson | LibVF.IO: vGPU & SR-IOV on Consumer GPUs using Nim | @dom96  |
| rlipsc | Polymorph: a compile time approach to entity-component-systems in Nim | @pietroppeter |
| scott wadden | Potato Zombies - Helping a 6 year old build a 3d game using Enu and Nim | @moigagoo |
| oakes | Pararules - A Nim rules engine for reactive programs and games | @pietroppeter |
| ayman-albaz | From Python to Nim, a preliminary introduction to performance optimization | @PMunch |
| pietroppeter | State of Scientific Computing in Nim 2022 | @moigagoo |
| treeform | Real World Metaprogramming with Nim  | @PMunch  |

(Happy to make that happen if everybody else is busy)

**Comment by dom96** [comment]
Alternatively we can also use the inverse for hosts, that way we can enjoy the presentations we're moderating instead of having to watch them again (since hosts will need to review the videos ahead of time).

**Comment by PMunch** [comment]
That sounds like a good plan, so if I review yours you'll review mine? And @pietroppeter and @moigagoo can review each others talks as well?

**Comment by dom96** [comment]
Yeah, something like that would be nice. Any thoughts @pietroppeter @moigagoo @xigoi ?

**Comment by moigagoo** [comment]
Well, I don't have a talk, so I can review any talk really.

**Comment by pietroppeter** [comment]
Hi sorry for disappearing for a bit, lots to catch up and very little time. If I understand correctly the two proposals are:

1) moderator(aka host)/coordinator are the same
2) moderator(aka host)/coordinator are different and the pairs @PMunch/@dom96 and @moigagoo/@pietroppeter switch roles?

and the main task of coordinator now is to review and give ok for the submitted talks?
I am fine with both but probably we could proceed with option 2 with a required modification: for my talk @moigagoo could be both host and coordinator (or otherwise I would need to be reviewer of my own talk). Not hiding the fact that this would imply I need to review only one talk (the Potato Zombies one).

And I still have to do my presentation, which will not be ready before this weekend :(

Have not caught up yet on the time schedule issue but I would anyway go on and confirm that I can reduce length of my talk to compensate for increased duration of the talk by Ayman-Albaz.

**Comment by dom96** [comment]
Okay, since you're busy now @pietroppeter I will move forward with the second option and give you the least to review :)

I'm now glad I didn't submit a talk, I also have had so little time over January, but I'm happy to help with the remaining organisation now that I have a bit more time.

**Comment by moigagoo** [comment]
I won't lie, I'm a bit lost about what happens next. The event is just a week away but I haven't yet seen the talks I'm about to coordinate. Also, there seems to be a review stage before that? How do I review them? Do I need to?

**Comment by PMunch** [comment]
We need to watch the talks and check that they are okay. This is mainly checking for:
- Audio issues
- Video issues (ie. if the video suddenly goes black or distorted)
- Content violation (just make sure no-one have snuck porn or copyrighted material into a talk)

To review a video you simply go to the page for the event you are reviewing:
- [HPC from Python to Nim](https://penta.fosdem.org/submission/FOSDEM22/event/12770)
- [Nim concurrency](https://penta.fosdem.org/submission/FOSDEM22/event/12796)
- [Next generation micro-controller programming](https://penta.fosdem.org/submission/FOSDEM22/event/12844)
- [State of scientific computing in Nim 2022](https://penta.fosdem.org/submission/FOSDEM22/event/12845)
- [Pararules](https://penta.fosdem.org/submission/FOSDEM22/event/12840)
- [LibVF.IO: vGPU & SR-IOV on Consumer GPUs using Nim](https://penta.fosdem.org/submission/FOSDEM22/event/12538)
- [Polymorph: a compile time approach to entity-component-systems in Nim](https://penta.fosdem.org/submission/FOSDEM22/event/12839)
- [Nim Metaprogramming in the real world](https://penta.fosdem.org/submission/FOSDEM22/event/12500)
- [Potato Zombies](https://penta.fosdem.org/submission/FOSDEM22/event/12849)

Then scroll down to the video section, it will either be under the "Review" button or the "Final version" button (the uploader can also review their talk, this is a system that was originally built for reviewing the recording of the live talks which you where expected to do yourself as a speaker). If the video looks good make sure it is accepted and available under the "Final version" button. If the video has problems we need to contact the speaker and have them upload a fixed version.

As far as I know it's now only Scott Waddens talk "Potato Zombies" which should be missing, I got an email from him earlier today with a rough cut and he said he would have the final version up on Penta tonight. Ryan Lipscombe has said that he wanted to upload a version with better sound and a better performing demo, but I'm not sure whether or not that has been done yet. I've sent him an email about it.

**Comment by moigagoo** [comment]
@pietroppeter Thanks for the clarification! So, I now must review your talk on scientific Nim, right? I don't see it uploaded though:

> We are currently generating the video of this talk.

Does it mean I'm still misunderstanding something or the statement below isn't entirely correct?

> As far as I know it's now only Scott Waddens talk "Potato Zombies" which should be missing

**Comment by dom96** [comment]
Okay, so here is the formal assignment:

| Who | What | Hosts | Video Reviewer 
|-----|------|----------|----------|
| araq | Nim concurrency Past, Present and Future | @dom96 | @pietroppeter  |
| pmunch | Next generation micro-controller programming | @pietroppeter | @dom96 |
| arthurrasmusson | LibVF.IO: vGPU & SR-IOV on Consumer GPUs using Nim | @dom96 | @pietroppeter  |
| rlipsc | Polymorph: a compile time approach to entity-component-systems in Nim | @pietroppeter | @dom96 |
| scott wadden | Potato Zombies - Helping a 6 year old build a 3d game using Enu and Nim | @moigagoo | @pmunch |
| oakes | Pararules - A Nim rules engine for reactive programs and games | @pietroppeter | @dom96 |
| ayman-albaz | From Python to Nim, a preliminary introduction to performance optimization | @PMunch | @moigagoo |
| pietroppeter | State of Scientific Computing in Nim 2022 | @moigagoo | @PMunch |
| treeform | Real World Metaprogramming with Nim  | @PMunch  | @moigagoo |

I've changed the naming a little to make it clearer, as I was myself once again getting confused between moderator/coord/host and I think we just need different terms to make the distinction clear.

So under this list, the responsibilities are as follows:

* Video Reviewer - The person who is expected to review the video, **let's aim to have this done by EOD Tuesday.**
* Host - The person that will moderate the live session, hosting the Q&A and moderating the chat.

In terms of FOSDEM's roles this means we will all still be "coordinators" of every talk (which should give us all the ability to moderate at any time in case it's needed). I also added the "host" role for each person that is hosting each talk.

**Please verify that I've done this correctly and confirm that you are happy with these assignments (if you don't I will assume we need someone else)**

**Comment by dom96** [comment]
I also fixed the scheduling for @pietroppeter's talk, reduced time by 5 mins.

**Comment by PMunch** [comment]
Oh, I thought you and I where switching, so I've already reviewed the two talks pietroppeter is set to review. No worries though, I can review a couple more

**Comment by PMunch** [comment]
Not sure if you guys also got the e-mail telling us the reviews are late? They where due this weekend.. The talks that are not marked as reviewed yet are:
- [Next generation micro-controller progra...](https://penta.fosdem.org/submission/FOSDEM22/event/12844)
- [Polymorph: a compile time approach to e...](https://penta.fosdem.org/submission/FOSDEM22/event/12839)
- [Potato Zombies](https://penta.fosdem.org/submission/FOSDEM22/event/12849)
- [State of Scientific Computing in Nim 20...](https://penta.fosdem.org/submission/FOSDEM22/event/12845)

I'll review the "State of Scientific.." talk right now. And I've checked that my talk looks okay as well (but feel free to review it again). Scott had some issues uploading "Potato Zombies" but is in [contact with the FOSDEM video team](https://github.com/FOSDEM/video/issues/197) so hopefully that's resolved soon. That means it's only the Polymorph talk left, @dom96 if you don't have time to do that one *today* I can do that one as well.

I'll also send out an e-mail to our speakers who just got that e-mail and tell them that everything is under control and that no further action from their end is required.

**Comment by pietroppeter** [comment]
Hi guys,
I am very sorry but I will not be able to complete my talk for Fosdem. it has been a complex January and the nail in the coffin was Covid in the whole family two weeks ago which entirely oblitared all my free time and left me with a lot of catchup on other fronts. It did not help that I had chosen to propose a talk for which material was not prepared (won't do that anymore). I am not sure yet what will the impact on the schedule, I will try to look into that and propose a solution but this mean that there is no more need to review my talk. I will still put in the time to review Potato Zombies and to host and coordinate on Saturday.

**Comment by PMunch** [comment]
That's unfortunate to hear, especially because of the circumstances. But don't beat yourself up about it, things like this happen. I'm not sure how we would go about de-scheduling a talk, I guess we might have to contact FOSDEM. We should also move the talk after yours up a slot and confirm with the speaker that they'll be able to be there at that time.

"Potato zombies" still has some unresolved issues with the upload as far as I can tell, if those are resolved without you being able to review it I can probably get that reviewed as well.

**Comment by dom96** [comment]
Thanks @PMunch! Sorry about the mis-alignment there. I will review polymorph today.

Are we happy with the host assignments? @pietroppeter will you still be able to do that part? no worries if not, we can take care of it and don't worry about your talk :)

@PMunch just to make sure we're aligned, you'll be taking care of de-scheduling @pietroppeter's talk?

**Comment by PMunch** [comment]
I'm fine with the host assignment.

Not sure how much @pietroppeter is able to do, he still has to review my talk (or assign that to someone else). I can take care of descheduling his talk.

**Comment by pietroppeter** [comment]
hi just checking on my tasks, especially the video reviewing which I understand are required to be done by Tuesday:
- from @PMunch previous comment I gather I should review his talk. I did watch it using the review link and submitted the "all good" feedback (nice set up you have and the library sounds very cool! a detail that caught my eye was the crown lingering on top of your head like a halo :D)
- from @dom96 's table I see instead I should be doing the video review of the talks by Araq and Rasmusson but the video review link there does not bring me to the same interface (it seems they are already reviewed). I am watching them anyway

**Comment by pietroppeter** [comment]
after (re)viewing the talks by Araq and Rasmusson I see a potential issue on the presentation by Rasmusson on LibVF.io (no issue as expected with Araq's talk). It seems to me that the presentation is a bit off topic with respect to Nim Devroom. While the open source library https://github.com/Arc-Compute/libvf.io is indeed made with Nim, there is no mention of Nim during the talk* (except for a single passing reference while talking about contributor Zedeus). I fear Nim Devroom is not the appropriate venue for the presentation as is and I would like to hear the opinions on this by @PMunch and @dom96 (we probably could discuss this on the private Matrix chat).

*up until minute 17 I listened to the whole talk, after that I skimmed the rest and noted that the word Nim does not appear in any slide and it does not seem to come up in the rest of the presentation.

**Comment by pietroppeter** [comment]
I have also listened to presentation on Polymorph (which appears still to be reviewed since review link works) and it seems to me there might be a video issue where discussion of last slide is cut (slide appears but is not discussed like previous slides). If I try to select "the video has problems" and submit I get an error (I guess this is not how it works? "video has problems" should be selected only when you can upload a new version?).

**Comment by pietroppeter** [comment]
ok, (re)viewed also presentation about pararules and no issue there (presentation is great as expected). I also change the state of my presentation to canceled and it has indeed disappeared from the website. We yet need to address the hole in the schedule: https://fosdem.org/2022/schedule/track/nim_programming_language/

**Comment by pietroppeter** [comment]
added 5 more minutes to HPC presentation duration (from 25 to 30 since video duration is 25 and we need 5 minutes for Q&A). we should check all video durations (we will have to wait for Potato Zombies) and if for all presentation we have the 5 minutes for Q&A we should just move up last presentation by treeform. I will do a brief check now

**Comment by pietroppeter** [comment]
these are just notes about timings:

author | topic | video duration | total duration | notes
---|---|---|---|---
araq | concurrency | 25:34 | 35 | almost 10' of Q&A
pmunch | microcontrollers | 29:38 | 35 | almost exactly 5' of Q&A
arthurrasmusson | libVF.io | 31:29 | 45 | we have almost 15' of Q&A (but maybe off topic?)
rlipsc | polymorph | 17:54 | 25 | very good: 7' Q&A (why pres length set to 0'?)
Scott Wadden (dsrw) | potato zombies | ? | 50 | issue with upload, video not yet available
Oakes | pararules | 36:04 | 50 | 14' of Q&A
aymanalbaz | hpc | 25 | 30 | pres length is still 15' tried changing to 25' but does not work not sure if that is an issue
treeform | metaprogramming | 31:16 | 35 | around 4' of Q&A

for scheduling purposes to make sure that Q&A time is > 5' and < 10' we could:
- remove 5' of duration from presentation by arthurasmusson (or we could ask to add something about Nim?)
- remove 5' from duration of pararules (would still leave around 9' for Q&A)
- add 5' of duration to treeform's talk (to make sure we have > 5' of Q&A)

other outstanding issues:
- video for potato zombies missing
- video on libVF.io potentially off topic
- video on polymorph possibly cut before the end

**Comment by dsrw** [comment]
My video (Potato Zombies) should be available now. It’s 36:26 in duration.

**Comment by pietroppeter** [comment]
* for finalisation of schedule see WIP https://github.com/pietroppeter/fosdem2022/pull/13/files
* talk by libvf.io is fine and not offtopic as discussed in private matrix chat
* talk by rlipsc is currently being fixed and extended and might have an increased length

for reference this would be the updated schedule (as in the above PR):

| Who | What | Video duration | Total Duration | Q&A duration (approx) | When |
 |-----|------|----------|---|-------------|---|
 | araq | Nim concurrency Past, Present and Future | 25:34 | 35' | 9' |12:30 - 13:05 |
 | pmunch | Next generation micro-controller programming | 29:38 | 35' | 5' | 13:05 - 13:40 |
 | arthurrasmusson | LibVF.IO: vGPU & SR-IOV on Consumer GPUs using Nim | 31:29 | 40' | 9' | 13:40 - 14:20 |
 | rlipsc | Polymorph: a compile time approach to entity-component-systems in Nim | _up to 35'_  | 40' | | 14:20 - 15:00 |
 | scott wadden | Potato Zombies - Helping a 6 year old build a 3d game using Enu and Nim | 36:26 | 45' | 9' | 15:00 - 15:45 |
 | oakes | Pararules - A Nim rules engine for reactive programs and games | 36:04 | 45' | 9' | 15:45 - 16:30 |
 | ayman-albaz | From Python to Nim, a preliminary introduction to performance optimization | 25:00 | 30' | 5' | 16:30 - 17:00 |
 | treeform | Real World Metaprogramming with Nim | 31:16 | 40' | 9' | 17:00 - 17:40 |

**Comment by pietroppeter** [comment]
with the merged schedule and the hosts decided in this issue (created a [moderator.md](moderator.md) document) this issue can be considered closed. I also updated readme to provide the timeline up to now and links to relevant documents
